# NUMPY (numerical python)

* Package for numerical computations, process multidimensional array

# NumPy Arrays

* Number of dimensions of the array is the rank of the array
* The shape of an array is a tuple of integers giving the size of the array in each dimension


In [1]:
import numpy as np

In [6]:
myList=[1,2,3,4,5,6]
arr = np.array(myList,dtype = int)
print(arr)
print(type(arr))
print(len(arr))
print(arr.ndim)
print(arr.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
6
1
(6,)


In [16]:
arr2 = arr.reshape(3,2)
print(arr2)
arr2.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [12]:
arr3 = arr.reshape(2,-1)
print(arr3)
arr3.ndim

[[1 2 3]
 [4 5 6]]


2

In [21]:
list1 = [3,5,2,5,3]
list2 = [5,5,2,4,8]
list3 = [9,5,2,5,7]
mul_arr = np.array([list1,list2,list3])
print(mul_arr)
print(mul_arr.shape)

[[3 5 2 5 3]
 [5 5 2 4 8]
 [9 5 2 5 7]]
(3, 5)


In [24]:
a = np.array([[5,6,7],[8,9,10]])
a.shape = (3,2)
print(a)

[[ 5  6]
 [ 7  8]
 [ 9 10]]


In [26]:
r = range(25)
print(r)

range(0, 25)


In [33]:
# an array of evenly spaced numbers
r1 = np.arange(24)
print(r1)
print(r1.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [35]:
b=r1.reshape(6,4,1)
print(b)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


In [36]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [38]:
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]


In [39]:
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [40]:
print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [42]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [43]:
print(np.sum(x))

10


In [44]:
#performing operations on columns
print(np.sum(x, axis=0))

[4 6]


In [45]:
#performing operations on rows

print(np.sum(x, axis = 1))

[3 7]


In [47]:
sample = np.array('d',[1,2,4])
print(sample)

TypeError: data type not understood

In [51]:
a= np.arange(1,10)
print(a[6::-3])

[7 4 1]
